// Central map of backend API route paths, grouped by feature.
// Query/mutation hooks import from here instead of hardcoding strings,
// so a path only ever needs to change in one place.
export const ENDPOINTS = {
  sales: {
    overview: '/sales/overview',
  },
  auth: {
    register: '/auth/register',
    login: '/auth/login',
    logout: '/auth/logout',
    refreshToken: '/auth/refresh-token',
    me: '/auth/me',
  },
  rawMaterials: {
    list: '/raw-materials',
    create: '/raw-materials',
    detail: (id) => `/raw-materials/${id}`,
    update: (id) => `/raw-materials/${id}`,
    remove: (id) => `/raw-materials/${id}`,
    lots: (id) => `/raw-materials/${id}/lots`,
    createLot: (id) => `/raw-materials/${id}/lots`,
    markWastage: (id, lotId) => `/raw-materials/${id}/lots/${lotId}/wastage`,
    allLots: '/raw-materials/lots',
    updateLotPayment: (lotId) => `/raw-materials/lots/${lotId}/payment`,
  },
  batches: {
    list: '/batches',
    create: '/batches',
  },
  readyStock: {
    list: '/ready-stock',
    history: (id) => `/ready-stock/${id}/history`,
  },
  areas: {
    list: '/areas',
    detail: (id) => `/areas/${id}`,
    create: '/areas',
    update: (id) => `/areas/${id}`,
    stores: (id) => `/areas/${id}/stores`,
    createStore: (id) => `/areas/${id}/stores`,
  },
  stores: {
    list: '/stores',
    unassigned: '/stores/unassigned',
    update: (id) => `/stores/${id}`,
    updateStatus: (id) => `/stores/${id}/status`,
    bulkAssign: '/stores/bulk-assign',
    bulkUnassign: '/stores/bulk-unassign',
  },
  orders: {
    list: '/orders',
    create: '/orders',
    updateStatus: (id) => `/orders/${id}/status`,
    fulfill: (id) => `/orders/${id}/fulfill`,
    orderTakerStats: '/orders/order-taker-stats',
  },
  walkInSales: {
    list: '/walk-in-sales',
    create: '/walk-in-sales',
    settle: (id) => `/walk-in-sales/${id}/settle`,
  },
  workers: {
    list: '/workers',
    detail: (id) => `/workers/${id}`,
    create: '/workers',
    update: (id) => `/workers/${id}`,
    remove: (id) => `/workers/${id}`,
    leave: (id) => `/workers/${id}/leave`,
    reactivate: (id) => `/workers/${id}/reactivate`,
  },
  schedule: {
    day: '/schedule',
    today: '/schedule/today',
    assignment: (workerId) => `/schedule/assignment/${workerId}`,
  },
  delivery: {
    status: '/delivery/status',
    scheduleDay: '/delivery/schedule',
    scheduleToday: '/delivery/schedule/today',
    setAreas: (driverId) => `/delivery/schedule/${driverId}`,
    driverDay: (id) => `/delivery/drivers/${id}/day`,
    driverStats: (id) => `/delivery/drivers/${id}/stats`,
  },
  attendance: {
    list: '/attendance',
    mark: '/attendance',
    clear: (workerId, date) => `/attendance/${workerId}/${date}`,
  },
  advances: {
    list: '/advances',
    create: '/advances',
    remove: (id) => `/advances/${id}`,
  },
  salaryPayments: {
    list: '/salary-payments',
    payroll: '/salary-payments/payroll',
    markPaid: '/salary-payments',
    bulkMarkPaid: '/salary-payments/bulk',
    markUnpaid: (workerId, year, month) => `/salary-payments/${workerId}/${year}/${month}`,
  },
  expenses: {
    list: '/expenses',
    create: '/expenses',
    remove: (id) => `/expenses/${id}`,
  },
  taxEntries: {
    list: '/tax-entries',
    create: '/tax-entries',
    remove: (id) => `/tax-entries/${id}`,
  },
  uploads: {
    receiptUrl: '/uploads/receipt-url',
  },
}
